# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: SCHEDULE-NEW

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "10 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci

  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Run Project
        env:
          BILIBILI_JCT: ${{ secrets.BILIBILI_JCT }}
          USERID: ${{ secrets.USERID }}
          SESSDATA: ${{ secrets.SESSDATA }}
        run:  |
          git config --local user.email "xiaoxiunique@gmail.com"
          git config --local user.name "atom.hu"
          npm ci && node index.js ${BILIBILI_JCT} ${SESSDATA} ${USERID}
          git add .
          git commit -m "update by github action"
          git push
